# Generated by Django 4.2.8 on 2025-05-14 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Areas',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Authors',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('price', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('barcode_number', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusname', models.TextField(blank=True, max_length=255, null=True)),
                ('gender', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Customers',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.TextField(blank=True, max_length=255, null=True)),
                ('role', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.TextField(blank=True, max_length=255, null=True)),
                ('gender', models.TextField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('hiredate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubname', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Publishers',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pickupdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Reservations',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfname', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.areas')),
            ],
            options={
                'verbose_name': 'Shelves',
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.CreateModel(
            name='Imports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('impprice', models.TextField(blank=True, max_length=255, null=True)),
                ('total', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.books')),
                ('id_pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.publishers')),
            ],
            options={
                'verbose_name': 'Imports',
                'verbose_name_plural': 'Imports',
            },
        ),
        migrations.CreateModel(
            name='Bookshelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.books')),
                ('id_shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.shelves')),
            ],
            options={
                'verbose_name': 'Bookshelves',
                'verbose_name_plural': 'Bookshelves',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='id_pub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.publishers'),
        ),
        migrations.CreateModel(
            name='Bookcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.books')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.categories')),
            ],
            options={
                'verbose_name': 'Bookcategories',
                'verbose_name_plural': 'Bookcategories',
            },
        ),
        migrations.CreateModel(
            name='Bookauthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.authors')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.books')),
            ],
            options={
                'verbose_name': 'Bookauthors',
                'verbose_name_plural': 'Bookauthors',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalbill', models.TextField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.customers')),
            ],
            options={
                'verbose_name': 'Bills',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Billdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.TextField(blank=True, max_length=255, null=True)),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.books')),
            ],
            options={
                'verbose_name': 'Billdetails',
                'verbose_name_plural': 'Billdetails',
            },
        ),
    ]
