# Generated by Django 4.2.8 on 2025-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4G', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publishers',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
