# Generated by Django 4.2.8 on 2025-05-15 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B4G', '0002_areas_description_authors_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetails',
            name='id_bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='B4G.bills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
