# Generated by Django 4.2.8 on 2025-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4G', '0003_billdetails_id_bill_billdetails_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookname',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
