# Generated by Django 4.2.8 on 2025-05-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B4G', '0004_books_bookname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='id_book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='B4G.books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='id_cus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='B4G.customers'),
            preserve_default=False,
        ),
    ]
