# Generated by Django 4.2.8 on 2025-05-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('B4G', '0005_reservations_id_book_reservations_id_cus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='B4G.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='auth.group', verbose_name='Primary Role'),
        ),
    ]
