# Generated by Django 4.2.8 on 2025-05-21 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('B4G', '0006_employees_id_user_userprofile_primary_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='id_book',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='id_cus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.customers', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='pickupdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Reservation Date'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='status',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ReservationItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastmodified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B4G.books', verbose_name='Book')),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='B4G.reservations', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Reservation Item',
                'verbose_name_plural': 'Reservation Items',
            },
        ),
    ]
