# Generated by Django 4.2.8 on 2025-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B4G', '0007_alter_reservations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, help_text='AI analysis confidence (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='ai_extracted_authors',
            field=models.TextField(blank=True, help_text='Authors extracted by AI (JSON format)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='ai_extracted_title',
            field=models.TextField(blank=True, help_text='Title extracted by AI from cover', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='ai_suggested_category',
            field=models.CharField(blank=True, help_text='Category suggested by AI analysis', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Book cover image for AI analysis', null=True, upload_to='book_covers/'),
        ),
        migrations.AddField(
            model_name='books',
            name='damage_details',
            field=models.TextField(blank=True, help_text='Detailed damage assessment (JSON format)', null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='damage_status',
            field=models.CharField(choices=[('none', 'No Damage'), ('minor', 'Minor Wear'), ('moderate', 'Moderate Damage'), ('severe', 'Severe Damage')], default='none', help_text='Book damage assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='books',
            name='last_ai_analysis',
            field=models.DateTimeField(blank=True, help_text='When AI analysis was last performed', null=True),
        ),
    ]
